/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedArqueoRouteImport } from './routes/_authenticated/arqueo'
import { Route as AuthenticatedEntradaRouteImport } from './routes/_authenticated/entrada'
import { Route as AuthenticatedSalidaRouteImport } from './routes/_authenticated/salida'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArqueoRoute = AuthenticatedArqueoRouteImport.update({
  id: '/arqueo',
  path: '/arqueo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntradaRoute = AuthenticatedEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalidaRoute = AuthenticatedSalidaRouteImport.update({
  id: '/salida',
  path: '/salida',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/arqueo': typeof AuthenticatedArqueoRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/salida': typeof AuthenticatedSalidaRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/arqueo': typeof AuthenticatedArqueoRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/salida': typeof AuthenticatedSalidaRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/arqueo': typeof AuthenticatedArqueoRoute
  '/_authenticated/entrada': typeof AuthenticatedEntradaRoute
  '/_authenticated/salida': typeof AuthenticatedSalidaRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/arqueo' | '/entrada' | '/salida' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/arqueo' | '/entrada' | '/salida' | '/settings' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/arqueo'
    | '/_authenticated/entrada'
    | '/_authenticated/salida'
    | '/_authenticated/settings'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arqueo': {
      id: '/_authenticated/arqueo'
      path: '/arqueo'
      fullPath: '/arqueo'
      preLoaderRoute: typeof AuthenticatedArqueoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entrada': {
      id: '/_authenticated/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof AuthenticatedEntradaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salida': {
      id: '/_authenticated/salida'
      path: '/salida'
      fullPath: '/salida'
      preLoaderRoute: typeof AuthenticatedSalidaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedArqueoRoute: typeof AuthenticatedArqueoRoute
  AuthenticatedEntradaRoute: typeof AuthenticatedEntradaRoute
  AuthenticatedSalidaRoute: typeof AuthenticatedSalidaRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArqueoRoute: AuthenticatedArqueoRoute,
  AuthenticatedEntradaRoute: AuthenticatedEntradaRoute,
  AuthenticatedSalidaRoute: AuthenticatedSalidaRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
